In [35]:
import pandas as pd
import seaborn
import requests
baseUrl = '/home/jovyan/work/datasets'

Requirements:
- New indicators:
    - [DATA](https://basecamp.com/1756858/projects/16224488/messages/87398455)  
        USD per day  
        Poverty line  
        Electricity access  
        Cooking energy  
        Salary‎ formally paid  
        Transactions (we will have to work with overalls here)  
        Mobile money (we will have to work with overalls here)  
        Asset ladder (Lifestyle - 3 categories.)  
        Water  
        Hunger symptom  
        Health symptom  
        Education symptom  
        Toilet type  

- New Section: **SMME (Small, Medium and Micro-sized Enterprises)** . 
    - [DATA](https://basecamp.com/1756858/projects/16224488/messages/87399105)  
          
        This will be a new interface for businesses, the current interface is for consumers only.

        The new indicators for this survey are;

        Employees (total)  
        Jurisdiction  
        Urb/rur  
        Gender of owner – Total will be the number of owners   
        Age of owner  
        Business size  
        Business development measure  
        Business age -  this will determine the age if the business   
        Registration/ Licenced – a few categories   
        Financial records  
        Sector – a few categories   
        Ownership structure – a few categories   
        Motives for starting a business  
        Skills – a few categories   
        Business coaching  
        Capital used to start 
        Infrastructure – a few categories  
        Financial inclusion (Banked, Other formal, Informal, Credit, Savings, Insurance, Transactions, MM account) – a few categories   
        Barriers from starting business– a few categories   
        Biggest obstacle to growing business  


*Actions:*
* New indicators; 
    - are they on the same format that the rest of the data?
    - Check feaseability of the new indicators to be uploaded to the api

* New Section; 
    - are they on the same format that the rest of the data?
    - Possible visualizations

# New indicators

In [ ]:
"""
This object will be use as the reference one. not all datasets will have the same columns. this object will be created once and will grow after each run of the algorithm.
allways trim and substitute empty values by null ones
{
colName:{ acceptedN: [set of similars built with every new one] each column will have its own why,
          acceptedV:{ valA: [set of similars built with every new one] each column will have its own why}
          toGetrid: "years"
          cat: True
          json: {
            "indicatorId": "geographic_area",
            "childIndicatorId": null,
            "answerId": null
        }
    }
}
"""

def uploadFunction(info):
    """
    Recive info as an dict with:
    {
    iso:
    year:
    fileUrl:
    jsonUrl:    
    }
    """
    url = 'http://i2i.vizzuality.com/api/v1/country/{iso}/{year}/dataset'.format(iso=info["iso"],year=info["year"])
    files1 = {'json': open(info["jsonUrl"], 'rb'), 'csv': open(info["fileUrl"], 'rb')}
    r = requests.post(url, files=files1)
    return r.json()

In [10]:
NewIndicators = pd.read_excel(f'{baseUrl}/i2i/newDatav5-6/FS Myanmar 2018 Final Data Set Shortened 13Sep19 final.xlsx')
NewIndicators.head(5)

,ID,Weight_Ind,Jurisdiction,Gender,Urb_rur,Banked,Other_Formal,Informal,FAS,Credit_B,...,Basic_assets,Asset_ladder,USD_per_day,Electricity_access,Cooking_energy,Education_symptom,Hunger_symptom,Health_symptom,Toilet_type,Water_source_type
0,1,4070.864692,Yangon,Female,Rural,NaN,NaN,Informal,Informal only,NaN,...,People with basic assets,Middle class segment,$1.91 - $6.65 per day,No electricity connection,Firewood,NaN,NaN,NaN,Pour flush to septic tank or pit,Unprotected dug well
1,2,2580.878114,Yangon,Female,Rural,NaN,NaN,Informal,Informal only,NaN,...,People with basic assets,Middle class segment,No income,Has electricity connection,Charcoal,NaN,NaN,Experienced medical symptom - SDG 3,Pour flush to septic tank or pit,Protected dug well
2,3,17116.483380,Yangon,Male,Rural,NaN,Other formal (non-bank),Informal,Other formal (non-bank),NaN,...,People with basic assets,Middle class segment,No income,No electricity connection,Liquefied petroleum gas,NaN,Experienced hunger symptom - SDG 1,NaN,Pour flush to septic tank or pit,Tubed/piped well or borehole
3,4,3627.829699,Yangon,Female,Rural,NaN,NaN,NaN,Excluded,NaN,...,People with basic assets,People with basic assets,Under $1.90 per day,No electricity connection,Charcoal,NaN,NaN,NaN,Pour flush to septic tank or pit,Water bought from taker truck or vendor
4,5,8051.798947,Yangon,Male,Rural,NaN,Other formal (non-bank),Informal,Other formal (non-bank),NaN,...,People with basic assets,Middle class segment,$6.66 per day and above,No electricity connection,Charcoal,NaN,NaN,Experienced medical symptom - SDG 3,Pour flush to septic tank or pit,Unprotected dug well

In [9]:
NewIndicators.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 51 columns):
ID                       5500 non-null int64
Weight_Ind               5500 non-null float64
Jurisdiction             5500 non-null object
Gender                   5500 non-null object
Urb_rur                  5500 non-null object
Banked                   1414 non-null object
Other_Formal             1889 non-null object
Informal                 2788 non-null object
FAS                      5500 non-null object
Credit_B                 810 non-null object
Credit_F                 987 non-null object
Credit_Inf               1310 non-null object
Credit_FF                742 non-null object
Credit_strand            5500 non-null object
Remittances_B            310 non-null object
Remittances_F            570 non-null object
Remittances_Inf          112 non-null object
Remittances_FF           172 non-null object
Remittances_strand       5500 non-null object
Savings_B                357 non-null object
Savings_F                398 non-null object
Savings_Inf              1885 non-null object
Savings_AH               1259 non-null object
Savings_strand           5500 non-null object
Transactions_B           661 non-null object
Transactions_MM          124 non-null object
Transactions_F           250 non-null object
Transactions_strand      5500 non-null object
Insurance_B              0 non-null float64
Insurance_F              303 non-null object
Insurance_Inf            647 non-null object
Insurance_strand         5500 non-null object
Mobile_money             149 non-null object
i2i_Sources_of_income    5500 non-null object
i2i_Education            5500 non-null object
i2i_Marital_status       5500 non-null object
i2i_Age                  5500 non-null object
Formally_employed        370 non-null object
Poverty_line             4665 non-null object
Comfortable_assets       1341 non-null object
Average_assets           4883 non-null object
Basic_assets             5064 non-null object
Asset_ladder             5500 non-null object
USD_per_day              4665 non-null object
Electricity_access       5500 non-null object
Cooking_energy           5500 non-null object
Education_symptom        352 non-null object
Hunger_symptom           340 non-null object
Health_symptom           831 non-null object
Toilet_type              5500 non-null object
Water_source_type        5500 non-null object
dtypes: float64(2), int64(1), object(48)
memory usage: 2.1+ MB

### Ensure that the current indicators and filters has the same formats as expected.

In [34]:
dfvaris=[[NewIndicators,NewIndicators.columns.values,'mmr2018']]
for i, data in enumerate(dfvaris):
    poblacion = sum(data[0]['Weight_Ind'])
    mujeres = data[0][data[0]['Gender'] == 'Female']
    total_mujeres = sum(mujeres['Weight_Ind'])
    hombres = data[0][data[0]['Gender'] == 'Male']
    total_hombres = sum(hombres['Weight_Ind'])
    print('_________________ ',data[2])
    print('Mujeres: ',total_mujeres)
    print('Hombres: ',total_hombres)
    print('Total: ', poblacion)

_________________  mmr2018
Mujeres:  17404908.815523382
Hombres:  16918254.54906298
Total:  34323163.36458628

In [32]:
for column in NewIndicators.columns:
    if column not in ['ID','Formally_employed','Poverty_line', 'Comfortable_assets', 'Average_assets', 'Basic_assets',
       'Asset_ladder', 'USD_per_day', 'Electricity_access', 'Cooking_energy',
       'Education_symptom', 'Hunger_symptom', 'Health_symptom', 'Toilet_type',
       'Water_source_type']:
        print(NewIndicators.groupby(column)[column].count())
        print('_________________________________________________________')

Weight_Ind
141.686340      1
150.315910      1
182.883605      1
194.252319      1
210.519349      1
               ..
24059.076350    1
24421.467530    1
24546.352050    1
25871.581470    1
26958.502680    1
Name: Weight_Ind, Length: 4240, dtype: int64
_________________________________________________________
Jurisdiction
Ayeyawady      620
Bago           500
Chin           170
Kachin         170
Kayah          170
Kayin          170
Magway         410
Mandalay       650
Mon            200
Nay Pyi Taw    170
Rakhine        210
Sagaing        540
Shan           550
Tanintharyi    170
Yangon         800
Name: Jurisdiction, dtype: int64
_________________________________________________________
Gender
Female    3441
Male      2059
Name: Gender, dtype: int64
_________________________________________________________
Urb_rur
Rural    3800
Urban    1700
Name: Urb_rur, dtype: int64
_________________________________________________________
Banked
Banked    1414
Name: Banked, dtype: int64
_________________________________________________________
Other_Formal
Other formal (non-bank)    1889
Name: Other_Formal, dtype: int64
_________________________________________________________
Informal
Informal    2788
Name: Informal, dtype: int64
_________________________________________________________
FAS
Banked                     1414
Excluded                   1624
Informal only              1216
Other formal (non-bank)    1246
Name: FAS, dtype: int64
_________________________________________________________
Credit_B
From bank    810
Name: Credit_B, dtype: int64
_________________________________________________________
Credit_F
From other formal (non-bank)    987
Name: Credit_F, dtype: int64
_________________________________________________________
Credit_Inf
From informal    1310
Name: Credit_Inf, dtype: int64
_________________________________________________________
Credit_FF
From family and friends    742
Name: Credit_FF, dtype: int64
_________________________________________________________
Credit_strand
From bank                        810
From family and friends          363
From informal                    759
From other formal (non-bank)     711
Not borrowing                   2857
Name: Credit_strand, dtype: int64
_________________________________________________________
Remittances_B
Through bank    310
Name: Remittances_B, dtype: int64
_________________________________________________________
Remittances_F
Through other formal (non-bank)    570
Name: Remittances_F, dtype: int64
_________________________________________________________
Remittances_Inf
Through informal channels    112
Name: Remittances_Inf, dtype: int64
_________________________________________________________
Remittances_FF
Through family and friends    172
Name: Remittances_FF, dtype: int64
_________________________________________________________
Remittances_strand
Not remitting                      4404
Through bank                        310
Through family and friends          163
Through informal channels           100
Through other formal (non-bank)     523
Name: Remittances_strand, dtype: int64
_________________________________________________________
Savings_B
At bank    357
Name: Savings_B, dtype: int64
_________________________________________________________
Savings_F
At other formal (non-bank)    398
Name: Savings_F, dtype: int64
_________________________________________________________
Savings_Inf
Informally    1885
Name: Savings_Inf, dtype: int64
_________________________________________________________
Savings_AH
At home    1259
Name: Savings_AH, dtype: int64
_________________________________________________________
Savings_strand
Not saving                         2772
Savings at bank                     357
Savings at home                     528
Savings informal                   1495
Savings other formal (non-bank)     348
Name: Savings_strand, dtype: int64
_________________________________________________________
Transactions_B
Using bank    661
Name: Transactions_B, dtype: int64
_________________________________________________________
Transactions_MM
Using Mobile Money    124
Name: Transactions_MM, dtype: int64
_________________________________________________________
Transactions_F
Using other formal (non-bank)    250
Name: Transactions_F, dtype: int64
_________________________________________________________
Transactions_strand
Cash transactions                4666
Using bank                        661
Using other formal (non-bank)     173
Name: Transactions_strand, dtype: int64
_________________________________________________________
Series([], Name: Insurance_B, dtype: int64)
_________________________________________________________
Insurance_F
From other formal (non-bank)    303
Name: Insurance_F, dtype: int64
_________________________________________________________
Insurance_Inf
From informal sources    647
Name: Insurance_Inf, dtype: int64
_________________________________________________________
Insurance_strand
From informal sources            535
From other formal (non-bank)     303
Not insured                     4662
Name: Insurance_strand, dtype: int64
_________________________________________________________
Mobile_money
Mobile Money    149
Name: Mobile_money , dtype: int64
_________________________________________________________
i2i_Sources_of_income
Farming and fishing               1141
Formally employed - Government     171
Formally employed - Private         95
Government dependent                 1
Informally employed                211
No income                         1237
Other income                       836
Remittances dependent              792
Self employed                     1016
Name: i2i_Sources_of_income, dtype: int64
_________________________________________________________
i2i_Education
No formal education                  759
Primary education                   2218
Secondary education                 2125
Tertiary education                   353
Vocational‎/Specialised training      45
Name: i2i_Education, dtype: int64
_________________________________________________________
i2i_Marital_status
Divorced/Separated          145
Married/Living together    4054
Single/Never married        746
Widowed                     555
Name: i2i_Marital_status, dtype: int64
_________________________________________________________
i2i_Age
18-24     865
25-35    1122
35-44    1363
45-60    1153
60>       997
Name: i2i_Age, dtype: int64
_________________________________________________________

## Lets explore the new ones

In [30]:
newCols = NewIndicators[['Formally_employed','Poverty_line', 'Comfortable_assets', 'Average_assets', 'Basic_assets',
       'Asset_ladder', 'USD_per_day', 'Electricity_access', 'Cooking_energy',
       'Education_symptom', 'Hunger_symptom', 'Health_symptom', 'Toilet_type',
       'Water_source_type']]
newCols.head(5)

,Formally_employed,Poverty_line,Comfortable_assets,Average_assets,Basic_assets,Asset_ladder,USD_per_day,Electricity_access,Cooking_energy,Education_symptom,Hunger_symptom,Health_symptom,Toilet_type,Water_source_type
0,Formally employed (SDG 8),Above poverty line ($1.90 per day),NaN,Middle class segment,People with basic assets,Middle class segment,$1.91 - $6.65 per day,No electricity connection,Firewood,NaN,NaN,NaN,Pour flush to septic tank or pit,Unprotected dug well
1,NaN,Below poverty line ($1.90 per day),NaN,Middle class segment,People with basic assets,Middle class segment,No income,Has electricity connection,Charcoal,NaN,NaN,Experienced medical symptom - SDG 3,Pour flush to septic tank or pit,Protected dug well
2,NaN,Below poverty line ($1.90 per day),NaN,Middle class segment,People with basic assets,Middle class segment,No income,No electricity connection,Liquefied petroleum gas,NaN,Experienced hunger symptom - SDG 1,NaN,Pour flush to septic tank or pit,Tubed/piped well or borehole
3,NaN,Below poverty line ($1.90 per day),NaN,NaN,People with basic assets,People with basic assets,Under $1.90 per day,No electricity connection,Charcoal,NaN,NaN,NaN,Pour flush to septic tank or pit,Water bought from taker truck or vendor
4,NaN,Above poverty line ($1.90 per day),NaN,Middle class segment,People with basic assets,Middle class segment,$6.66 per day and above,No electricity connection,Charcoal,NaN,NaN,Experienced medical symptom - SDG 3,Pour flush to septic tank or pit,Unprotected dug well

In [31]:
for colum in newCols.columns:
    print(newCols.groupby(colum)[colum].count())
    print('_________________________________________________________')

Formally_employed
Formally employed (SDG 8)    370
Name: Formally_employed, dtype: int64
_________________________________________________________
Poverty_line
Above poverty line ($1.90 per day)    2672
Below poverty line ($1.90 per day)    1993
Name: Poverty_line, dtype: int64
_________________________________________________________
Comfortable_assets
People living comfortably/affluent    1341
Name: Comfortable_assets, dtype: int64
_________________________________________________________
Average_assets
Middle class segment    4883
Name: Average_assets, dtype: int64
_________________________________________________________
Basic_assets
People with basic assets    5064
Name: Basic_assets, dtype: int64
_________________________________________________________
Asset_ladder
Middle class segment                  3560
None                                   150
People living comfortably/affluent    1341
People with basic assets               449
Name: Asset_ladder, dtype: int64
_________________________________________________________
USD_per_day
$1.91 - $6.65 per day      1653
$6.66 per day and above    1019
No income                  1237
Under $1.90 per day         756
Name: USD_per_day, dtype: int64
_________________________________________________________
Electricity_access
Has electricity connection    3089
No electricity connection     2411
Name: Electricity_access, dtype: int64
_________________________________________________________
Cooking_energy
Charcoal                                             500
Firewood                                            3253
Household generator                                    1
Liquefied petroleum gas                               45
Other                                                 48
Private-provided electricity (private generator)      73
Publicly-provided electricity / city power          1546
Solar power                                            1
Village Power                                         33
Name: Cooking_energy, dtype: int64
_________________________________________________________
Education_symptom
Experienced education symptom - SDG 4    352
Name: Education_symptom, dtype: int64
_________________________________________________________
Hunger_symptom
Experienced hunger symptom - SDG 1    340
Name: Hunger_symptom, dtype: int64
_________________________________________________________
Health_symptom
Experienced medical symptom - SDG 3    831
Name: Health_symptom, dtype: int64
_________________________________________________________
Toilet_type
Latrine overhanging field or water                   64
None                                                244
Pit latrine with slab                              1056
Pit latrine without slab or open pit                120
Pour flush to elsewhere (not sewer or pit/tank)     118
Pour flush to septic tank or pit                   3898
Name: Toilet_type, dtype: int64
_________________________________________________________
Water_source_type
Bottled-water / water dispenser                     6
Improved rainwater collection /catchment tank      46
Outside piped or public tap                       343
Piped in dwelling or on premises                  802
Pond, lake, river or stream                       850
Protected dug well                                215
Tubed/piped well or borehole                     2426
Unimproved rainwater collection                    24
Unprotected dug well                              658
Water bought from taker truck or vendor           130
Name: Water_source_type, dtype: int64
_________________________________________________________

In [38]:
url = 'http://i2i.vizzuality.com/api/v1/indicator'
r = requests.get(url)
r.json()

ConnectionError: HTTPConnectionPool(host='i2i.vizzuality.com', port=80): Max retries exceeded with url: /api/v1/indicator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9745fd1c18>: Failed to establish a new connection: [Errno 110] Connection timed out'))

In [ ]:
useJson =json.loads("""{
    "weightColumn": "Weight_Ind",
    "indicators":{
        "Urb_Rur": {
            "indicatorId": "geographic_area",
            "childIndicatorId": null,
            "answerId": null
        },
        "Province":{
            "indicatorId": "jurisdiction",
            "childIndicatorId": null,
            "answerId": null
        },
        "M_D3": {
            "indicatorId": "gender",
            "childIndicatorId": null,
            "answerId": null
        },
        "i2i_Age": {
            "indicatorId": "age",
            "childIndicatorId": null,
            "answerId": null
        },
        "i2i_Marital_Status":{
            "indicatorId": "i2i_Marital_Status",
            "childIndicatorId": null,
            "answerId": null
        },
        "i2i_Education": {
            "indicatorId": "i2i_Education",
            "childIndicatorId": null,
            "answerId": null
        },
        "i2i_Source_of_Income": {
            "indicatorId": "i2i_Income_Sources",
            "childIndicatorId": null,
            "answerId": null
        },
        "Banked": {
            "indicatorId": "fas_strand",
            "childIndicatorId": null,
            "answerId": 1
        },
        "Other_formal": {
            "indicatorId": "fas_strand",
            "childIndicatorId": null,
            "answerId": 2
        },
        "Informal": {
            "indicatorId": "fas_strand",
            "childIndicatorId": null,
            "answerId": 3
        },
        "fas_access": {
            "indicatorId": "fas_strand",
            "childIndicatorId": null,
            "answerId": 4
        },
        "Saving_B":{
            "indicatorId": "savings_strand",
            "childIndicatorId": null,
            "answerId": 1
        },
        "Saving_F":{
            "indicatorId": "savings_strand",
            "childIndicatorId": null,
            "answerId": 2
        },
        "Saving_Inf":{
            "indicatorId": "savings_strand",
            "childIndicatorId": null,
            "answerId": 3
        },
        "Saving_AH":{
            "indicatorId": "savings_strand",
            "childIndicatorId": null,
            "answerId": 4
        },
        "saving_access":{
            "indicatorId": "savings_strand",
            "childIndicatorId": null,
            "answerId": 5
        },
        "Remittances_B":{
            "indicatorId": "remittances_strand",
            "childIndicatorId": null,
            "answerId": 1
        },
        "Remittances_F":{
            "indicatorId": "remittances_strand",
            "childIndicatorId": null,
            "answerId": 2
        },
        "Remittances_Inf":{
            "indicatorId": "remittances_strand",
            "childIndicatorId": null,
            "answerId": 3
        },
        "Remittances_FF":{
            "indicatorId": "remittances_strand",
            "childIndicatorId": null,
            "answerId": 4
        },
        "remittances_access":{
            "indicatorId": "remittances_strand",
            "childIndicatorId": null,
            "answerId": 5
        },
        "Insurance_F":{
            "indicatorId": "insurance_strand",
            "childIndicatorId": null,
            "answerId": 1
        },
        "Insurance_Inf":{
            "indicatorId": "insurance_strand",
            "childIndicatorId": null,
            "answerId": 2
        },
        "Insurance_B":{
            "indicatorId": "insurance_strand",
            "childIndicatorId": null,
            "answerId": 3
        },
        "insurance_access":{
            "indicatorId": "insurance_strand",
            "childIndicatorId": null,
            "answerId": 4
        },
        "Credit_B":{
            "indicatorId": "credit_strand",
            "childIndicatorId": null,
            "answerId": 1
        },
        "Credit_F":{
            "indicatorId": "credit_strand",
            "childIndicatorId": null,
            "answerId": 2
        },
        "Credit_Inf":{
            "indicatorId": "credit_strand",
            "childIndicatorId": null,
            "answerId": 3
        },
        "Credit_FF":{
            "indicatorId": "credit_strand",
            "childIndicatorId": null,
            "answerId": 4
        },
        "credit_access":{
            "indicatorId": "credit_strand",
            "childIndicatorId": null,
            "answerId": 5
        },
        "Weight_Ind":{
            "indicatorId": "weight_ind",
            "childIndicatorId": null,
            "answerId": null
        },
        "FAS":{
            "indicatorId": "total_fas_strand",
            "childIndicatorId": null,
            "answerId": 1
        },
        "Saving_Strand":{
            "indicatorId": "total_saving_strand",
            "childIndicatorId": null,
            "answerId": 2
        },
        "Remittances_Strand":{
            "indicatorId": "total_remittances_strand",
            "childIndicatorId": null,
            "answerId": 3
        },
        "Insurance_Strand":{
            "indicatorId": "total_insurance_strand",
            "childIndicatorId": null,
            "answerId": 4
        },
        "Credit_Strand":{
            "indicatorId": "total_credit_strand",
            "childIndicatorId": null,
            "answerId": 5
        }
    }
}""")